-- GENERAL CONSTANTS --
DEVELOPER_MODE = true
TEXTURE_BASE_SIZE = 32
BACKGROUND_VARIANTS = 1
NUM_OVERLAY_TEXTURES = 15
NUM_CONNECTED_TEXTURE_TILES = 2
STATE_CONFIGURATIONS = {[1]=1,[5]=2,[21]=3,[85]=4,[17]=5,[29]=6,[113]=7,[93]=8,[125]=9,[7]=10,[31]=11,[127]=12,[255]=13,[119]=14,[0]=15}

function file_exists(name)
   if love.filesystem.getInfo(name) then return true
   else return false end
end

local function enum(n,i)
  i = i or 1
  if n > i then
    return i, enum(n,i+1)
  end
  return n
end

-- ENUM CONSTANTS --
NUM_TYPES = 7
TYPE_WALL, TYPE_GLASS, TYPE_SOURCE, TYPE_RECEIVER, TYPE_MIRROR, TYPE_PWHEEL, TYPE_PRISM = enum(NUM_TYPES)

NUM_COLORS = 8
COLOR_RED, COLOR_GREEN, COLOR_YELLOW, COLOR_BLUE, COLOR_MAGENTA, COLOR_CYAN, COLOR_WHITE, COLOR_BLACK = enum(NUM_COLORS)

NUM_CURSOR_MODES = 4
CURSOR_MOVE, CURSOR_ROTATE, CURSOR_INTERACT, CURSOR_SELECT = enum(NUM_CURSOR_MODES)
